config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  root 'posts#index'
  namespace :admin do
    get :sign_up, to: 'users#new'
    post :sign_up, to: 'users#create'
    
    get :sign_in, to: 'sessions#new'
    post :sign_in, to: 'sessions#create'
    
    get :sign_out, to: 'sessions#destroy'
    
   
    resources :posts
    root to: 'posts#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ActiveRecord::Base
  serialize :tags
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate
  helper_method :sign_in?, :current_user
  
  layout "admin"
  def sign_in?
    !!session[:user_id]
  end 
  
  def sign_in user
    session[:user_id]=user.id
  end 
  
  def sign_out
    session[:user_id]=nil
  end 
  
  def current_user
    User.find(session[:user_id]) if (session[:user_id])
  end 
  
  def authenticate
    unless sign_in?
      redirect_to admin_sign_in_path
    end 
  end 
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  
  def index
    @posts = Post.all
    
  end 
  def show
    @posts = Post.all
    
  end 
  def new
     @post = Post.new
  end 
  
  def create
      @post = Post.new(post_params)
      if @post.save
       redirect_to admin_root_path
      else
        render 'new'
      end 
  end
  
  def edit
     @post = Post.find(params[:id])
  end 
  
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    if @post.save
     redirect_to admin_root_path
    else
      render 'edit'
    end 
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_root_path
  end
  
  private
    def post_params
      params.require(:post).permit(:title,:author,:content,:published_at)
    end 
  
  
end 

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController <  Admin::BaseController
  skip_before_filter :authenticate, only: [:new, :create]
  
  def new
    @user = User.new
  end 
  
  def create
    @user=User.where(email: params[:user][:email]).first
    if @user && @user.authenticate(params[:user][:password])
      sign_in @user 
      redirect_to admin_root_path
    else
      redirect_to admin_sign_in_path
    end
  end 
  def destroy
    sign_out
    redirect_to root_path
  end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController <  Admin::BaseController
  skip_before_filter :authenticate, only: [:new, :create]
  
  def new
    @user = User.new
  end 
  
  def create
      @user = User.new(user_params)
      if @user.save
       sign_in @user
       redirect_to admin_root_path
      else
        render 'new'
      end 
  end 
  
  private
    def user_params
      params.require(:user).permit(:email,:nickname,:password,:password_confirmation)
    end 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = if params[:category]
      Post.joins(:categories).where(categories: {id: params[:category]})
    else
      Post.all
    end
  end
 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/edit.html.erb
<div class="blog-header">
  <h1 class="blog-title">Edit a Post</h1>
</div>

<%= form_for(@post,url: admin_post_path(@post)) do |f| %>
  <div class="form-group">
    <label for="post_title">Title</label>
    <%= f.text_field :title,class: "form-control",placeholder:"Title" %>
  </div>
  
  <div class="form-group">
    <label for="post_author">Author</label>
    <%= f.text_field :author,class: "form-control",placeholder:"Author" %>
  </div>
  <div class="form-group">
    <label for="post_content">Content</label>
    <%= f.text_area :content,class: "form-control wysihtml5",placeholder:"Content" %>
  </div>
  <div class="form-group">
    <label for="post_published_at">Published At</label>
    <%= f.datetime_field :published_at,class: "form-control",placeholder:"Published At" %>
  </div>
 
  <%= f.submit "Update", class: "btn btn-default" %>
<% end %>

app/views/admin/posts/index.html.erb
<table class="table table-striped table-hover datatatble">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>Published</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th> <%= post.id %></th>
        <td><%= post.title %></td>
        <td><%= post.author %></td>
        <td><%= l post.published_at %></td>
        <td>
          <%= link_to "Edit",edit_admin_post_path(post) %>
          <%= link_to "Delete",admin_post_path(post), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<div class="blog-header">
  <h1 class="blog-title">Create a Post</h1>
</div>

<%= form_for(@post,url: admin_posts_path) do |f| %>
  <div class="form-group">
    <label for="post_title">Title</label>
    <%= f.text_field :title,class: "form-control",placeholder:"Title" %>
  </div>
  
  <div class="form-group">
    <label for="post_author">Author</label>
    <%= f.text_field :author,class: "form-control",placeholder:"Author" %>
  </div>
  <div class="form-group">
    <label for="post_content">Content</label>
    <%= f.text_area :content,class: "form-control",placeholder:"Content" %>
  </div>
  <div class="form-group">
    <label for="post_published_at">Published At</label>
    <%= f.datetime_field :published_at,class: "form-control",placeholder:"Published At" %>
  </div>
 
  <%= f.submit "Create", class: "btn btn-default" %>
<% end %>

app/views/admin/users/new.html.erb
<div class="blog-header">
  <h1 class="blog-title">Sign Up</h1>
</div>

<%= form_for(@user,url: admin_sign_up_path) do |f| %>
  <div class="form-group">
    <label for="user_email">Email address</label>
    <%= f.email_field :email,class: "form-control",placeholder:"Email" %>
  </div>
  
  <div class="form-group">
    <label for="user_nickname">Nickname</label>
    <%= f.text_field :nickname,class: "form-control",placeholder:"Nickname" %>
  </div>
  <div class="form-group">
    <label for="user_password">Password</label>
    <%= f.password_field :password,class: "form-control",placeholder:"Password" %>
  </div>
  <div class="form-group">
    <label for="user_password_confirmation">Password confirmation</label>
    <%= f.password_field :password_confirmation,class: "form-control",placeholder:"Password confirmation" %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-default" %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/3.3/favicon.ico">

    <title>Blog Template for Bootstrap</title>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/admin">Posts</a>
          <a class="blog-nav-item " href="/admin/posts/new">Create a Post</a>
         
          <%= link_to("Sign Out",admin_sign_out_path,class:"blog-nav-item pull-right") %>
         
         
        </nav>
      </div>
    </div>

    <div class="container">

      <%= yield %>
    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <%= javascript_include_tag "application" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/3.3/favicon.ico">

    <title>Blog Template for Bootstrap</title>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          
          <% Category.all.each do |category| %>
          
            <%= link_to category.name,posts_path(category: category.id), class:"blog-nav-item" %></a>
          
          <% end %>
          <a class="blog-nav-item" href="#">About</a>
          
        </nav>
      </div>
    </div>

    <div class="container">

      <%= yield %>
    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <%= javascript_include_tag "application" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </body>
  
</html>

app/views/posts/index.html.erb
<div class="blog-header">
  <h1 class="blog-title">The Bootstrap Blog</h1>
  <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
</div>

<div class="row">

  <div class="col-sm-8 blog-main">
  <% @posts.each do |post| %>

    <div class="blog-post">
      <h2 class="blog-post-title"><%= post.title %></h2>
      <p class="blog-post-meta"><%= l post.published_at %> by <%= post.author %>
      
      <br>
      <% post.categories.each do |category| %>
        <span class="label label-default"><%= category.name %></span>
      <% end %>
      </p>
    <%= sanitize post.content %>
     
    </div><!-- /.blog-post -->
  <% end -%>
    <nav>
      <ul class="pager">
        <li><a href="#">Previous</a></li>
        <li><a href="#">Next</a></li>
      </ul>
    </nav>

  </div><!-- /.blog-main -->

  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>
    <div class="sidebar-module">
      <h4>Archives</h4>
      <ol class="list-unstyled">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
        <li><a href="#">December 2013</a></li>
        <li><a href="#">November 2013</a></li>
        <li><a href="#">October 2013</a></li>
        <li><a href="#">September 2013</a></li>
        <li><a href="#">August 2013</a></li>
        <li><a href="#">July 2013</a></li>
        <li><a href="#">June 2013</a></li>
        <li><a href="#">May 2013</a></li>
        <li><a href="#">April 2013</a></li>
      </ol>
    </div>
    <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </div><!-- /.blog-sidebar -->

</div><!-- /.row -->